#..Spring
spring:
  application:
    name: eureka-service

#..Server
server:
  port: 8761
  error:
    include-message: always
    include-binding-errors: always

#..Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    prefer-ip-address: true
